import Paths;
import flixel.FlxG;
import flixel.FlxSprite;
import flixel.util.FlxTimer;
import flixel.tweens.FlxTween;
import flixel.tweens.FlxEase;
import flixel.text.FlxText;
import flixel.util.FlxColor;
#if desktop
import Discord.DiscordClient;
#end
import flixel.addons.display.FlxBackdrop;
import openfl.filters.ShaderFilter;
import openfl.display.Shader;
import flixel.addons.transition.FlxTransitionableState;
import flixel.util.FlxGradient;
import flixel.system.FlxAssets.FlxShader;
import haxe.Timer;
import Sys;
import sys.FileSystem;
import flixel.input.FlxSwipe;
import flixel.input.touch.FlxTouch;
import openfl.utils.Assets;
import openfl.system.System;